from pydantic import BaseModel, EmailStr

class ContactBase(BaseModel):
    name : str
    phone_number : str
    email : EmailStr

class ContactCreate(ContactBase):
    pass

class Contact(ContactBase):
        id : int 
        #id is autogenerated by db
        class Config:
            orm_mode = True

